### ISSUE TITLE
Not all textures are extracted from xfbin file

### ISSUE THREAD

**Issue by mixe21** [maxcabd/NUT-Tools#2]
xfbin contains two textures 3hanbody.nut and 3hanbody_lod1.nut with the same name, but only one of them is extracted.
![screen](https://user-images.githubusercontent.com/66806604/179435134-b6eb4228-a3da-4140-8905-bfc11535febe.jpg)
Noesis can't convert them to dds and throws four error: WARNING: Unknown texture format 6.

Here is the file [3hanbod1.out.zip](https://github.com/maxcabd/nut-tools/files/9126580/3hanbod1.out.zip)

**Comment by maxcabd** [comment]
This isn't really an issue. I just didn't include an option to also dump alternate textures yet.
